title:       nukeop.github.io
author:      nukeop
description: A technology-oriented blog.

markdown:    kramdown
highlighter: rouge
paginate:    5

exclude:
  - LICENSE

plugins:
  - jekyll-paginate
