title:       nukeop.github.io
author:      nukeop
description: Description of the static website.

markdown:    kramdown
highlighter: rouge
paginate:    5

exclude:
  - LICENSE

plugins:
  - jekyll-paginate
